apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: asaiapp-deploy
  name: asaiapp-deploy
  namespace: asaiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asaiapp-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asaiapp-deploy
    spec:
      
      containers:
      - name: asaiapp
        #image: shoeb0005/asaiapp
        image: shoeb0005/asaiapp:${TAG_NAME}
        
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: asaiapp-deploy
  name: asaiapp-deploy-svc
  namespace: asaiapp
spec:
  ports:
  - name: asaiapp-port 
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31080
  selector:
    app: asaiapp-deploy
  type: NodePort
status:
  loadBalancer: {}
